name: Auto Link Repair

on:
  schedule:
    - cron: '*/10 * * * *' # 10 நிமிடத்திற்கு ஒருமுறை
  workflow_dispatch:      # மேனுவலாக இயக்க

jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          MAC: ${{ secrets.MAC_ADDR }}
          SN: ${{ secrets.SERIAL_NO }}
          DID: ${{ secrets.DEVICE_ID }}
        run: python new-update.py

